version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing source NPM dependencies
      - npm install
  build:
    commands:
      - echo Build started
      - npm run build
  post_build:
    commands:
      - ls -R ./dist
      - aws s3 cp --recursive ./build s3://tasks2-bucket/
      - aws s3 cp --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/index.html s3://tasks2-bucket/
      - aws cloudfront create-invalidation --distribution-id E149WYPVDR4U4F --paths /index.html
artifacts:
  files:
    - 'build/*'
    - 'build/**/*'
